### PR TITLE
Update plugin infrastructure and dependencies

### PR DESCRIPTION
**Pull request by daffl**
This pull request upgrades all dependencies to the latest version and updates the plugin infrastructure with the upgrade to Feathers 5 to follow.

### CODE REVIEW

**Comment by daffl** [comment]
Currently still a draft since remote service authentication is not working yet for some reason.

**Comment by daffl** [comment]
@claustres Do you have any thoughts why the authentication test is failing? I believe the way it has been set up should work.

**Comment by claustres** [comment]
@daffl It seems to me it was actually a bug in the tests: we were authenticating a client on one of the service app using the local strategy while it should only be available on the gateway app, service app should only have JWT strategy. I don't know how it was possible to work previously.

**Review by claustres — COMMENTED** [review]
Seems ready to merge, will see with the next PR why 2 tests are failting

**Pull request merged**
