### PR TITLE
upgrade feathers v3

### PR DESCRIPTION
**Pull request by Flofie**
### Summary

This PR upgrades the project to feathers v3

### CODE REVIEW

**Comment by Flofie** [comment]
Hmm some tests are failing again :-( 
I hade the same issue on my machine but blamed it on the same strange async bug I had lasttime.
The strange thing is that the service itself seams to be working fine. I tested it with docker and everything worked as expected.

**Comment by Flofie** [comment]
My mistake, I forgot to register the new channels function for realtime communication

**Comment by Flofie** [comment]
had to revert back to feathers-memory 2.1.0 since 2.1.1 requires clone-depp 3.0.0 which require min. node 8.

**Comment by claustres** [comment]
Thanks for this great PR, I will have a look at it as soon as possible and will create a `auk` branch for the previous version using Feathers 2.x.

**Pull request merged**
